spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    pl.tomaszosuch.trainingplatform_backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha