CREATE TABLE workout_template
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint       NOT NULL,
    category_id  bigint       NOT NULL,
    name         varchar(200) NOT NULL,
    description  text,
    duration_min integer,
    created_at   timestamp(6) NOT NULL,
    updated_at   timestamp(6),

    CONSTRAINT workout_template_duration_check
        CHECK (duration_min IS NULL OR duration_min > 0)
);

ALTER TABLE workout_template
    ADD CONSTRAINT fk_workout_template_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE workout_template
    ADD CONSTRAINT fk_workout_template_category
        FOREIGN KEY (category_id) REFERENCES workout_category (id);

CREATE INDEX idx_workout_template_user
    ON workout_template (user_id);