CREATE TABLE cooperation
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id     bigint       NOT NULL,
    athlete_id   bigint       NOT NULL,
    status       varchar(20)  NOT NULL,
    created_at   timestamp(6) NOT NULL,
    responded_at timestamp(6),
    ended_at     timestamp(6),

    CONSTRAINT cooperation_status_check
        CHECK (status IN ('PENDING', 'ACTIVE', 'REJECTED', 'ENDED')),

    CONSTRAINT cooperation_not_self_check
        CHECK (coach_id <> athlete_id)
);

ALTER TABLE cooperation
    ADD CONSTRAINT fk_cooperation_coach
        FOREIGN KEY (coach_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE cooperation
    ADD CONSTRAINT fk_cooperation_athlete
        FOREIGN KEY (athlete_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE UNIQUE INDEX uq_cooperation_open_pair
    ON cooperation (coach_id, athlete_id) WHERE status IN ('PENDING', 'ACTIVE');

CREATE INDEX idx_cooperation_coach
    ON cooperation (coach_id, status);

CREATE INDEX idx_cooperation_athlete
    ON cooperation (athlete_id, status);