CREATE TABLE users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    birth_date  timestamp(6),
    created_at  timestamp(6)  NOT NULL,
    email       varchar(255)  NOT NULL,
    first_name  varchar(100)  NOT NULL,
    is_active   boolean       NOT NULL,
    last_name   varchar(100)  NOT NULL,
    password    varchar(255)  NOT NULL,
    role        varchar(20)   NOT NULL,
    updated_at  timestamp(6),
    CONSTRAINT users_role_check
        CHECK (role::text = ANY (ARRAY['USER'::varchar, 'ADMIN'::varchar]::text[]))
);

CREATE TABLE workout_category (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color      varchar(7),
    icon_name  varchar(255),
    name       varchar(100) NOT NULL
);

CREATE TABLE training_plan (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) NOT NULL,
    duration_min  integer,
    notes         text,
    planned_date  date         NOT NULL,
    planned_time  time(0),
    status        varchar(20)  NOT NULL,
    title         varchar(200) NOT NULL,
    updated_at    timestamp(6),
    category_id   bigint       NOT NULL,
    user_id       bigint       NOT NULL,
    CONSTRAINT training_plan_status_check
        CHECK (status::text = ANY (ARRAY['PLANNED'::varchar, 'COMPLETED'::varchar,
                                         'SKIPPED'::varchar, 'CANCELLED'::varchar]::text[]))
);

CREATE TABLE workout_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6) NOT NULL,
    duration_min    integer,
    intensity       integer,
    notes           text,
    performed_date  date         NOT NULL,
    updated_at      timestamp(6),
    category_id     bigint       NOT NULL,
    plan_id         bigint,
    user_id         bigint       NOT NULL,
    performed_time  time(0),
    title           varchar(255)
);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE workout_category
    ADD CONSTRAINT uk16wiu7i2pwtc4ur4powbgeucm UNIQUE (name);

ALTER TABLE training_plan
    ADD CONSTRAINT fkakdfy6q2i5e7jomdkfms446ds
    FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE training_plan
    ADD CONSTRAINT fk6m46npsb4xdkpmoylamgjucoj
    FOREIGN KEY (category_id) REFERENCES workout_category (id);

ALTER TABLE workout_log
    ADD CONSTRAINT fk5v4tkc8cpi78w36xk6ho6cf1y
    FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE workout_log
    ADD CONSTRAINT fk6e88vquqqp2c0xuqdhcdqq6no
    FOREIGN KEY (plan_id) REFERENCES training_plan (id);

ALTER TABLE workout_log
    ADD CONSTRAINT fks3oymklcotnra4tse7h0ywjyu
    FOREIGN KEY (category_id) REFERENCES workout_category (id);