CREATE TABLE invitation (
                            id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at  timestamp(6) NOT NULL,
                            email       varchar(255) NOT NULL,
                            expires_at  timestamp(6) NOT NULL,
                            revoked_at  timestamp(6),
                            role        varchar(20)  NOT NULL DEFAULT 'USER',
                            sent_at     timestamp(6),
                            token_hash  varchar(64)  NOT NULL,
                            used_at     timestamp(6),
                            invited_by  bigint       NOT NULL,
                            CONSTRAINT invitation_role_check
                                CHECK (role::text = ANY (ARRAY['USER'::varchar, 'ADMIN'::varchar]::text[]))
    );

ALTER TABLE invitation
    ADD CONSTRAINT uk_invitation_token_hash UNIQUE (token_hash);

ALTER TABLE invitation
    ADD CONSTRAINT fk_invitation_invited_by
        FOREIGN KEY (invited_by) REFERENCES users (id);

CREATE UNIQUE INDEX idx_invitation_pending_email
    ON invitation (email)
    WHERE used_at IS NULL AND revoked_at IS NULL;   