CREATE TABLE password_reset_token
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    expires_at timestamp(6) NOT NULL,
    token_hash varchar(64)  NOT NULL,
    used_at    timestamp(6),
    user_id    bigint       NOT NULL
);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash);

ALTER TABLE password_reset_token
    ADD CONSTRAINT fk_password_reset_token_user
        FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_password_reset_token_user
    ON password_reset_token (user_id);
