CREATE TABLE refresh_token
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL,
    token_hash  varchar(64)  NOT NULL,
    created_at  timestamp(6) NOT NULL,
    expires_at  timestamp(6) NOT NULL,
    revoked_at  timestamp(6),
    replaced_by bigint,
    user_agent  varchar(512)
);

ALTER TABLE refresh_token
    ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);

ALTER TABLE refresh_token
    ADD CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE refresh_token
    ADD CONSTRAINT fk_refresh_token_replaced_by
        FOREIGN KEY (replaced_by) REFERENCES refresh_token (id) ON DELETE SET NULL;

CREATE INDEX idx_refresh_token_user_active
    ON refresh_token (user_id, revoked_at);