CREATE TABLE goal
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint       NOT NULL,
    category_id    bigint,
    title          varchar(200) NOT NULL,
    description    text,
    metric         varchar(20)  NOT NULL,
    target_value   integer      NOT NULL,
    start_date     date         NOT NULL,
    end_date       date,
    achieved_at    timestamp(6),
    achieved_value integer,
    created_at     timestamp(6) NOT NULL,
    updated_at     timestamp(6),

    CONSTRAINT goal_metric_check
        CHECK (metric IN ('SESSIONS', 'MINUTES')),
    CONSTRAINT goal_target_value_check
        CHECK (target_value > 0),
    CONSTRAINT goal_window_check
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT goal_achieved_check
        CHECK ((achieved_at IS NULL) = (achieved_value IS NULL))
);

ALTER TABLE goal
    ADD CONSTRAINT fk_goal_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE goal
    ADD CONSTRAINT fk_goal_category
        FOREIGN KEY (category_id) REFERENCES workout_category (id);

CREATE INDEX idx_goal_user_achieved
    ON goal (user_id, achieved_at);